### ISSUE TITLE
Total Pile of junk...avoid at all costs.

### ISSUE THREAD

**Issue by hybridwebdev** [vkbansal/react-contextmenu#199]
Just making this as fair warning to those thinking about using this module...it doesn't work. Menu item click bind does nothing, meaning all this does is show a useless pop up menu that doesn't function. Followed provided examples to a tee, and onClick never fires...Thanks for wasting a few hours of my time creator. Hopefully this will save others the aggravation.

**Comment by ankeetmaini** [comment]
@hybridwebdev instead of railing, could you open a PR to fix things? It shows more on your part than the repository's maintainer. Writing components is hard, please acknowledge and appreciate it.

You've no right to demand anything here, we do it in our own time and you're not paying for this. So please keep the harsh words to yourself. This is an **awesome** component, hands down.

Going by the usage stats seems like everyone else got it working.
