### ISSUE TITLE
get the element from where the context menu was opened?

### ISSUE THREAD

**Issue by BramscoChill** [vkbansal/react-contextmenu#226]
I was wondering if it is possible to get the element from where you open the menu from (right click on), after clicking an MenuItem. I am using thing context menu in an treeview and need the origional target element.

I could not find this in the documentation. Am I missing somthing or is this not build in?

**Comment by daniellizik** [comment]
Typically it's considered an antipattern to send a ref outside the scope of a react component. See [this answer](https://stackoverflow.com/a/38864091/4769440) for more details.

That said, you can do this with plain React using `this.refs.<ref>`, it's not really specific to this package. However, I think the documentation could be improved upon since the method of passing props from `ContextMenuTrigger` to the menu is a bit convoluted; you have to read the examples to figure how to do that.

Here's an example of how to take a screenshot of a video through a context menu

```js
import { MenuItem, ContextMenuTrigger, connectedMenu } from 'react-contextmenu';
import react,  { Component } from 'react';

const Menu = () => connectedMenu('menu')(props => (
  <div>
    <MenuItem onClick={props.trigger.takeScreenshot()}>take screenshot</MenuItem>
  </div>
));

class ThingWithMenu  extend Component {
  takeScreenshot() {
    const { video } = this.refs;
    const canvas = react.createElement('canvas');
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;

    const ctx = canvas.getContext('2d');
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

    // do something with this
    const dataURI = canvas.toDataURL('image/jpeg');
  }

  render() {
    return (
      <div>
        <Menu />
        <ContextMenuTrigger collect={p => p} takeScreenshot={this.takeScreenshot} id="menu">
          <video ref="video"></video>
        </ContextMenuTrigger>
      </div>
    );
  }
}
```
The only important bit is using the `collect` callback prop on the menu trigger. If v3 ever gets released I hope that gets removed, I don't really see the point of it.

**Comment by daniellizik** [comment]
@BramscoChill doesn't seem like something that needs to be implemented in this package. You'd probably have to use `setState` to cache the current clicked element, then pass it to a connected menu.

```js
const Menu = () => connectedMenu('menu')(props => (
  <div>
    <MenuItem>node value: {props.trigger.nodeValue}</MenuItem>
  </div>
));

class TreeWithMenu extends Component {
  handleClick(val) {
    this.setState({ val });
  }

  render() {
    return (
      <div>
        <Menu />
        <ContextMenuTrigger collect={p => p} nodeValue={this.state.val} id="menu">
          <Tree>
            <div onClick={() => this.handleClick('foo')}>foo</div>
            <div onClick={() => this.handleClick('bar')}>bar</div>
          </Tree>
        </ContextMenuTrigger>
      </div>
    );
  }
}
```

I didn't test that, if the click bubbling doesn't work I'd use `mouseOver` to set state instead.
