### ISSUE TITLE
Does not work well for chrome 77 and 78(and Safari 13)

### ISSUE THREAD

**Issue by gFaro** [vkbansal/react-contextmenu#302]
I noticed react-contextmenu stopped working for me. I tried it in mozilla and it still works fine.

Not working on...
Google chrome version: 77/78.
Safari version: 13.03

react-contextmenu version: 2.13.0 (also didin't work on 2.11.0)

Note: I noticed that if I remove holdToDisplay={-1} then it works perfectly in mozilla but in chrome and safari it hides behind the native context menu.

The error is reproduced here (without holdToDisplay={-1}): https://codesandbox.io/s/flamboyant-margulis-4efxd.

**Comment by vkbansal** [comment]
The sandbox is working fine for me

```
Mac OS: 10.15.1 (19B88)
Chrome: Version 78.0.3904.97 (Official Build) (64-bit)
```

Can you provide more details about OS and browser?

**Comment by gFaro** [comment]
My browser is Chrome version 78.0.3904.97.

OS is MAC OS MOJAVE
version 10.14.6

Apologies for the delayed response.

**Comment by peerjollux** [comment]
I'm having the same issue. When use right click it works, but when using ctrl+click it shows the native contextmenu.

**My details:**
```
Mac OS: 10.15.0
Chrome: Version 78.0.3904.108 
```

**Comment by peerjollux** [comment]
I found what is causing the issue, it's because of the change in this commit:
https://github.com/vkbansal/react-contextmenu/commit/2220024e1f41457ee0f4c4114d989daa9b0d8d23#diff-8c52c6cf66a1c629f586678b831921a2

Because of this commit, it will only listen to mouse button clicks from Button 2.

I switched back to V2.10.0 as a temporary solution.
