### ISSUE TITLE
V2.0.0-alpha.2 menus don't show on Safari

### ISSUE THREAD

**Issue by philiphubbard** [vkbansal/react-contextmenu#41]
With v2.0.0-alpha.2 running in Safari (Version 9.0.3) on OS X (Version 10.11.3), a right click on a target does not produce any visible menu.  This problem is easily reproducible with any of the examples included in this project.  Earlier versions, like v1.6.2, do not have this problem, nor does v2.0.0-alpha.2 running on Chrome (Version 54.0.2840.71).

**Comment by vkbansal** [comment]
Will check this out

**Comment by alolis** [comment]
I tried out as well and it works normally under Safari `Version 10.0 (11602.1.50.0.10)`

**Comment by fjoliot** [comment]
Hello,
I tried it out on Safari 9.1.2 (OS X El Capitan 10.11.6) and the bug is present. The error I get in Safari's developer console when I try your simple menu demo 
is the following one :

![capture d ecran 2016-11-25 a 11 20 45](https://cloud.githubusercontent.com/assets/23737717/20622156/ce42ecba-b301-11e6-9d40-f60966c1d91e.png)


Thanks a lot for your help
