### ISSUE TITLE
Left Click Menu

### ISSUE THREAD

**Issue by darshanmodani** [vkbansal/react-contextmenu#50]
Can we put a configuration for left click or right click to `ContextMenuTrigger` so that contextmenu can also be invoked with left click ?

**Comment by vkbansal** [comment]
The main use of a context-menu menu is on right/context click. I believe that it is not a good idea to deviate from that.

You can use **dropdowns** if you want to show a menu on left click.

**Comment by lakshya-8** [comment]
@vkbansal I also think this `ContextMenuTrigger` should be configurable to be able to handle `Left/Right` click.

**Comment by vkbansal** [comment]
Can you give a good reason for allowing it?

**Comment by lakshya-8** [comment]
If I want to use this library to open the context-menu by left clicking on a three-dot ( e.g In Google Drive if you click on any of the folders, you'd see three-dot menu for that folder and left clicking opens the context-menu for that folder) menu.

**Comment by vkbansal** [comment]
Shouldn't that be dropdown-menu instead of context-menu? The three-dot menu has a fixed positions (i.e top-right) and a [simple dropdown menu can be created only using css](https://line25.com/tutorials/how-to-create-a-pure-css-dropdown-menu) for this case. It does not require the complex logic of calculating the position.

Where as for a context-menu, you don't have control over where a user will click, and hence it requires all the calculations.

I believe this should answer your query.

**Comment by danilvalov** [comment]
If someone wants to do this then just use the `holdToDisplay` option for `ContextMenuTrigger` with a value of `0`:
```js
<ContextMenuTrigger
  id='your-context-menu-id'
  holdToDisplay={0}
>
  <div>Test</div>
</ContextMenuTrigger>`
```

**Comment by eladrkatz** [comment]
vkbansal - technically you're right.. but if I'm already using this component in my app then for dropdown menu it's very convenient to use just one component.
It's not as if allowing the change of the triggering event would make the component more complex or anything...

**Comment by eladrkatz** [comment]
Makes me wonder how many of the 117 forks are just for this feature ;)

**Comment by vkbansal** [comment]
fine, I'll accept a PR

**Comment by ospfranco** [comment]
hey, is this merged? the readme doesn't seem to specify it

**Comment by hybridwebdev** [comment]
I wouldn't count on this being merged, as author seems hell bent on arguing with people as to why their needs are stupid/pointing out alternative options, rather than making ANY attempt to help people. I personally wasted a good chunk of my day trying to implement this feature based on his inaccurate documentation. I then filed an issue only to have him argue with me and then close the issue. Honestly, this repo should be closed/pulled as he's obviously got no intention of maintaining it or offering any sort of support.

**Comment by vkbansal** [comment]
> I wouldn't count on this being merged

@hybridwebdev do you see any PR that I can merge? Where is the PR?

**Comment by hybridwebdev** [comment]
It's YOUR software dude....how bout instead of expecting others to maintain it, you get off your butt and maybe work on HELPING people?

**Comment by vkbansal** [comment]
> It's YOUR software dude....how bout instead of expecting others to maintain it, you get off your butt and maybe work on HELPING people?

It's OPEN SOURCE!

Form WIKI:
The open-source model is a decentralized software-development model that encourages open collaboration. A main principle of open-source software development is **peer production**, with products such as source code, blueprints, and documentation freely available to the public.

Also READ the [License](https://github.com/vkbansal/react-contextmenu/blob/master/LICENSE.md)
