### ISSUE TITLE
Trigger menu from JavaScript

### ISSUE THREAD

**Issue by greggman** [vkbansal/react-contextmenu#76]
Sorry if this is a dumb question.

In any case is there a recommended way to show the menus from JavaScript myself?

It doesn't appear that `showMenu` and `hideMenu` are exported from `index.js`

It seems strange to use `<ContextMenuTrigger>` when contextmenu is an event. Would you make a `<Click>` component for left mouse clicks and ` <MouseMove>` component for mouse move events?

**Comment by whathejoe** [comment]
Try this solution

https://github.com/vkbansal/react-contextmenu/issues/46#issuecomment-262168214

**Comment by greggman** [comment]
thanks

**Comment by vkbansal** [comment]
The main `<ContextMenuTrigger>` exists because, it takes care of the custom logic like passing props to `<ContextMenu>` is handled automatically.

Tomorrow, for some unforeseen reason, if I decide to switch the internal implementation, the user must not have to take the burden of updating their `oncontextmenu` manually.

Hope this answers your query.

**Comment by greggman** [comment]
I see your point, and for a generic simple context menu that might make sense. 

Imagine you're making something similar to Picasa or Windows Explorer or the OSX File Manager or iPhoto. It makes no sense to mark up every file or thumbnail, 1000s of them, with a `<ContextMenuTrigger>`  Elements should have something more to do with how that element displays. Following this library's pattern if other libraries followed this style every element would have 5, 10, 20 wrappers

      <ContextMenuTrigger>  // if the user right clicks
         <ClickTrigger>   // if the user clicks
            <CopyPasteTrigger>  // if the user picks copy
                <DragAndDropTrigger>  // if the user drags and drops something here
                    <div id="actualnormalcontent">....

times 1000s. That's lots of redundant data, elements, all kinds of bloat, complicates CSS, etc...

Just suggesting that figuring out a way make a stable API for this use case might be a win.

**Comment by vkbansal** [comment]
`ContextMenuTrigger` has ` attributes` props, which are directly passed to the root element. So you can pass `onClick` and other things directly.

If you have had seen the [src of `ContexMenuTrigger`](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenuTrigger.js), you would have know that it encapsulates a lot of logic for handling touch events, which otherwise you would have to handle yourselfs.

If you don't like the approach, this package uses, you are free to not use it.

**Comment by greggman** [comment]
Sorry I tried to be helpful.

**Comment by vkbansal** [comment]
I'm sorry if I have offended you in anyway.

But instead of criticizing, you can been more helpful by actually putting a solution to it and opening a PR.
